# Generated by Django 3.1.3 on 2020-11-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=500)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created on date')),
            ],
        ),
    ]
