# Generated by Django 3.1.3 on 2020-11-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20201108_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us'},
        ),
    ]
