# Generated by Django 3.1.3 on 2020-11-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20201108_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
